name: Check Membership Pull Request
on:
  workflow_run:
    workflows: ["Receive PR Events"]
    types:
      - completed
jobs:
  check-membership-approvals:
    runs-on: ubuntu-latest
    outputs:
      membership-approvals-status: ${{ steps.pr-validation.outcome }}
    steps:
      - uses: actions/checkout@v3
      - name: Run PR validation
        id: pr-validation
        run: exit 0

  peribolos:
    runs-on: ubuntu-latest
    outputs:
      peribolos-check-status: ${{ steps.peribolos-check.outcome }}
    container:
      image: gcr.io/k8s-prow/peribolos
    steps:
      - uses: actions/checkout@v3
      - name: Check ODH organization membership
        id: peribolos-check
        run: exit 0

  merge-pr:
    runs-on: ubuntu-latest
    needs:
      - check-membership-approvals
      - peribolos
    steps:
      - name: Check results
        run: |
          echo "PR Validation Status: ${{ needs.check-membership-approvals.outputs.membership-approvals-status }}"
          echo "Peribolos Check Status: ${{ needs.peribolos.outputs.peribolos-check-status }}"
