name: Add Issues to ODH Feature Tracking Project
on:
  issues:
    types:
      - opened
jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage/needs-triage"]
            })
