name: Add Issues to ODH Feature Tracking Project
on:
  issues:
    types:
      - opened
jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          run: gh issue edit ${{ github.event.issue.number }} --add-label "triage/needs-triage"
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/anishasthana-testing-org/projects/1
          github-token: ${{ secrets.TOKEN }}
